version: "3.9"

services:
  kong:
    image: kong:3.7
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - users-service
      - items-service
      - orders-service
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
  users-service:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./users-service:/app
    environment:
      MODULE_NAME: main
    ports:
      - "8002:80"

  items-service:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./items-service:/app
    environment:
      MODULE_NAME: main
    ports:
      - "8003:80"

  orders-service:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./orders-service:/app
    environment:
      MODULE_NAME: main
    ports:
      - "8004:80"
